services:
  db:
    image: postgres:15
    restart: always
    env_file: .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - db
    env_file: .env.development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file: .env.development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend-dist:/app/dist
    working_dir: /app
    networks:
      - app-network
    command: npm run dev

  nginx:
    build: ./nginx
    depends_on:
      - frontend
      - backend
    env_file: .env.development
    ports:
      - "80:80"
    #volumes:
    #  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

volumes:
  pgdata:
  frontend-dist:


networks:
  app-network:
